version: '3.8'

services:
  spurtcms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spurtcms
    restart: unless-stopped
    ports:
      - "8082:8082"  # Main application port
      - "8083:8083"  # Preview port
      - "8085:8084"  # GraphQL port (changed to 8085 to avoid conflicts)
    volumes:
      - ./static_files:/app/storage  # Static files mapping
      - ./.env.docker:/app/.env  # Environment variables configuration
      - ./public:/app/public  # Map local public directory for JS/CSS debugging
    depends_on:
      - postgres
    environment:
      - DATABASE_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=spurtcms
      - DB_USERNAME=spurtcms
      - DB_PASSWORD=spurtcms_password
      - DB_SSL_MODE=disable
      - TIME_ZONE=Asia/Shanghai
    networks:
      - spurtcms_network

  postgres:
    image: postgres:14-alpine
    container_name: spurtcms_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=spurtcms
      - POSTGRES_PASSWORD=spurtcms_password
      - POSTGRES_DB=spurtcms
      # Allow connections from any host
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      # Use named volume for database storage
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spurtcms_network
    command: ["postgres", "-c", "listen_addresses=*"]

networks:
  spurtcms_network:
    driver: bridge

volumes:
  postgres_data:
    # Using a regular Docker volume instead of a bind mount
    # This will let Docker manage permissions properly
